import Foundation

enum SettingsStrings {
    static let windowTitle = "Settings"

    static let generalTabTitle = "General"
    static let shortcutsTabTitle = "Shortcuts"
    static let searchTabTitle = "Search"
    static let aboutTabTitle = "About"

    static let generalIntroTitle = "App Behavior"
    static let generalIntroMessage = "These controls define how Spotdark integrates with macOS. The skeleton is in place so behavior can be wired without changing the layout later."
    static let launchAtLoginTitle = "Launch at login"
    static let launchAtLoginHelp = "System integration will be connected in a follow-up task."
    static let menuBarTitle = "Show menu bar helper"
    static let menuBarHelp = "The menu bar entry remains available as a fallback launcher trigger."
    static let appearanceSectionTitle = "Appearance"
    static let appearancePickerTitle = "Window appearance"
    static let appearanceHelp = "Choose whether Spotdark follows the system appearance or stays pinned to light or dark mode."
    static let themePresetSectionTitle = "Color Presets"
    static let themePresetHelp = "Presets recolor the launcher immediately and stay active across relaunches."
    static let themePresetSelectedAccessibilityValue = "Selected"
    static let panelSectionTitle = "Launcher Panel"
    static let panelPositionTitle = "Remember last panel position"
    static let panelPositionHelp = "Panel positioning stays centered for now; this option reserves the future preference."

    static let shortcutsIntroTitle = "Global Hotkey"
    static let shortcutsIntroMessage = "Choose the launcher shortcut here. Updates are saved immediately and re-register the global listener without reopening the app."
    static let currentShortcutTitle = "Current shortcut"
    static let currentShortcutPrompt = "Click to change the launcher shortcut"
    static let recordingShortcutTitle = "Recording shortcut"
    static let recordingShortcutPrompt = "Press the new key combination now"
    static let recordingShortcutValue = "Type Shortcut"
    static let recordShortcutButton = "Record Shortcut"
    static let cancelShortcutRecordingButton = "Cancel"
    static let resetShortcutButton = "Reset to Default"
    static let shortcutReadyMessage = "Click the shortcut card or use the button to start recording."
    static let shortcutRecordingActiveMessage = "Recording is active. Press Escape to cancel without saving."
    static let shortcutRecordingCancelledMessage = "Shortcut capture cancelled."
    static let shortcutUpdatedMessage = "Shortcut updated and applied immediately."
    static let shortcutResetMessage = "Shortcut reset to the default launcher binding."
    static let shortcutRecordingHelp = "Use Control, Option, or Command with another key. Reserved macOS combinations are rejected before they are saved."
    static let shortcutPermissionFeedback = "Spotdark still needs Accessibility permission before the new shortcut can be registered globally."
    static let shortcutRegistrationFailedFeedback = "Spotdark could not register that shortcut. Try a different combination."
    static let shortcutValidationModifierRequired = "Add Control, Option, or Command to avoid intercepting normal typing."
    static let shortcutValidationReservedTemplate = "%@ is reserved by macOS. Choose a different combination."
    static let fallbackShortcutTitle = "Fallback shortcut"
    static let shortcutRulesTitle = "Recording Rules"
    static let shortcutRulesMessage = "System-reserved combinations like Spotlight and the app switcher stay blocked, while the default launcher binding remains available as a safe fallback."
    static let conflictHandlingTitle = "Shortcut conflict handling"
    static let conflictHandlingValue = "Reject reserved combos before saving"
    static let shortcutLiveUpdateTitle = "Apply changes"
    static let shortcutLiveUpdateValue = "Immediately"

    static let searchIntroTitle = "Search Scope"
    static let searchIntroMessage = "Choose which folders Spotdark scans for applications. Changes are saved immediately and refresh the index in place."
    static let defaultLocationsSectionTitle = "Default Locations"
    static let defaultLocationsHelp = "These bundled locations are always scanned and cannot be removed."
    static let customLocationsSectionTitle = "Custom Locations"
    static let customLocationsEmptyTitle = "No custom folders yet"
    static let customLocationsEmptyMessage = "Add folders like Setapp, external app bundles, or team-shared tool directories."
    static let addFolderButton = "Add Folder"
    static let removeFolderButton = "Remove Selected"
    static let moveFolderUpButton = "Move Up"
    static let moveFolderDownButton = "Move Down"
    static let customLocationsHelp = "Custom folders are stored in your settings and trigger a fresh app scan when they change."
    static let folderPickerTitle = "Choose an App Search Folder"
    static let folderPickerMessage = "Select a folder whose contents should be scanned for application bundles."
    static let folderPickerPrompt = "Add Folder"

    static let webSearchSectionTitle = "Web Search"
    static let webSearchEnginePickerTitle = "Default search engine"
    static let webSearchEngineHelp = "When no local results match, Spotdark offers a web search using this engine."

    static let aboutSectionTitle = "Spotdark"
    static let aboutHeadline = "Spotdark Settings"
    static let aboutSummary = "A settings skeleton for the macOS launcher, aligned with the existing glassy UI and ready for follow-up configuration work."
    static let roadmapSectionTitle = "Next UI Hooks"
    static let roadmapShortcutTitle = "Shortcut capture UI"
    static let roadmapShortcutSummary = "Will connect to the hotkey registration path without reworking navigation."
    static let roadmapSearchTitle = "Directory management"
    static let roadmapSearchSummary = "Custom folders now support add, remove, reorder, and immediate reindexing."
    static let roadmapFeedbackTitle = "Error feedback"
    static let roadmapFeedbackSummary = "Can surface registration and indexing failures in the same settings surface."

    static let systemAppearance = "Follow System"
    static let lightAppearance = "Light"
    static let darkAppearance = "Dark"
    static let themePresetOceanTitle = "Ocean"
    static let themePresetOceanSummary = "Cool blue glass with a crisp Spotlight-like accent."
    static let themePresetSunriseTitle = "Sunrise"
    static let themePresetSunriseSummary = "Warm amber highlights with a softer command palette feel."

    static let settingsMenuItemTitle = "Settings..."
    static let showLauncherMenuItemTitle = "Show Launcher"
    static let quitMenuItemTitle = "Quit"

    // Data management
    static let dataManagementSectionTitle = "Data Management"
    static let dataManagementHelp = "Export your settings as a portable JSON file or import one to restore a previous configuration."
    static let exportSettingsButton = "Export Settings…"
    static let importSettingsButton = "Import Settings…"
    static let exportSavePanelTitle = "Export Spotdark Settings"
    static let exportDefaultFilename = "Spotdark Settings"
    static let importOpenPanelTitle = "Import Spotdark Settings"
    static let importOpenPanelPrompt = "Import"

    // Import sheet
    static let importSheetTitle = "Import Settings"
    static let importSheetConflictsHeading = "The following settings differ from your current configuration:"
    static let importSheetNoConflictsMessage = "The imported file matches your current settings. No changes will be made."
    static let importSheetStrategyHeading = "How should conflicts be handled?"
    static let importReplaceAllButton = "Replace All"
    static let importMergeButton = "Merge (Keep Current)"
    static let importCancelButton = "Cancel"
    static let importReplaceAllHelp = "All settings are overwritten with values from the file."
    static let importMergeHelp = "Conflicting scalars keep your current value; custom folders and pinned items are combined."
    static let importAppliedMessage = "Settings imported successfully."

    // Import conflict field names
    static let importConflictHotkey = "Hotkey"
    static let importConflictAppearance = "Appearance"
    static let importConflictTheme = "Theme"
    static let importConflictMenuBar = "Menu Bar"
    static let importConflictPanelPosition = "Remember Panel Position"
    static let importConflictWebSearch = "Web Search Engine"
    static let importConflictSearchLocations = "Custom Search Folders"
    static let importConflictPinnedItems = "Pinned Items"
    static let importValueOn = "On"
    static let importValueOff = "Off"
    static let importConflictFolderCountTemplate = "%d folder(s)"
    static let importConflictItemCountTemplate = "%d item(s)"
}
