import Foundation

enum SettingsStrings {
    static let windowTitle = "Settings"

    static let generalTabTitle = "General"
    static let shortcutsTabTitle = "Shortcuts"
    static let searchTabTitle = "Search"
    static let aboutTabTitle = "About"

    static let generalIntroTitle = "App Behavior"
    static let generalIntroMessage = "These controls define how Spotdark integrates with macOS. The skeleton is in place so behavior can be wired without changing the layout later."
    static let launchAtLoginTitle = "Launch at login"
    static let launchAtLoginHelp = "System integration will be connected in a follow-up task."
    static let menuBarTitle = "Show menu bar helper"
    static let menuBarHelp = "The menu bar entry remains available as a fallback launcher trigger."
    static let appearanceSectionTitle = "Appearance"
    static let appearancePickerTitle = "Window appearance"
    static let appearanceHelp = "Theme persistence is reserved for a later phase."
    static let panelSectionTitle = "Launcher Panel"
    static let panelPositionTitle = "Remember last panel position"
    static let panelPositionHelp = "Panel positioning stays centered for now; this option reserves the future preference."

    static let shortcutsIntroTitle = "Global Hotkey"
    static let shortcutsIntroMessage = "Shortcut recording will plug into the existing hotkey registration flow in Phase 1-2."
    static let currentShortcutTitle = "Current shortcut"
    static let recordShortcutButton = "Record Shortcut"
    static let shortcutRecordingHelp = "Recording is not connected yet. This section defines the final placement and visual treatment."
    static let fallbackShortcutTitle = "Fallback shortcut"
    static let fallbackShortcutValue = "Option + Space"
    static let conflictHandlingTitle = "Shortcut conflict handling"
    static let conflictHandlingValue = "Show warning and keep a fallback shortcut ready"

    static let searchIntroTitle = "Search Scope"
    static let searchIntroMessage = "Folder configuration will be connected in Phase 1-3. This view already exposes the sections and affordances that task needs."
    static let defaultLocationsSectionTitle = "Default Locations"
    static let defaultLocationsHelp = "These are the bundled app discovery paths currently used by Spotdark."
    static let customLocationsSectionTitle = "Custom Locations"
    static let customLocationsEmptyTitle = "No custom folders yet"
    static let customLocationsEmptyMessage = "Add and remove actions will be enabled once directory persistence is wired."
    static let addFolderButton = "Add Folder"
    static let removeFolderButton = "Remove Selected"
    static let customLocationsHelp = "This section is reserved for user-managed search folders."

    static let aboutSectionTitle = "Spotdark"
    static let aboutHeadline = "Spotdark Settings"
    static let aboutSummary = "A settings skeleton for the macOS launcher, aligned with the existing glassy UI and ready for follow-up configuration work."
    static let roadmapSectionTitle = "Next UI Hooks"
    static let roadmapShortcutTitle = "Shortcut capture UI"
    static let roadmapShortcutSummary = "Will connect to the hotkey registration path without reworking navigation."
    static let roadmapSearchTitle = "Directory management"
    static let roadmapSearchSummary = "Will reuse the custom locations section for add/remove interactions."
    static let roadmapFeedbackTitle = "Error feedback"
    static let roadmapFeedbackSummary = "Can surface registration and indexing failures in the same settings surface."

    static let systemAppearance = "Follow System"
    static let lightAppearance = "Light"
    static let darkAppearance = "Dark"

    static let currentShortcutValue = "Command + Space"
    static let settingsMenuItemTitle = "Settings..."
    static let showLauncherMenuItemTitle = "Show Launcher"
    static let quitMenuItemTitle = "Quit"
}
